name: Upload Development Docker Container

run-name: Development Container build by @${{ github.triggering_actor }}

permissions:
  packages: write
  contents: read

on:
  push:
    branches:
      - feature/docker-container

jobs:
  build:
    name: Upload Container

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build
        run: docker build -t ghcr.io/volublerobin7/cocktailcollator:dev .

      - name: Push
        run: docker push ghcr.io/volublerobin7/cocktailcollator:dev

      - name: Print
        run: echo "The branch is ${{ github.ref }}"

  test:
    if: ${{ github.ref }} == 'refs/heads/development'

    name: Test Job

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v5